[package]
name = "helpers"
version = "0.1.0"
edition = "2021"
authors = ["Samuele Maci <macisamuele@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
clap = {version = "4", features = ["derive"]}
