default_language_version:
  python: python3.10

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.5.0 # v2.5.0
  hooks:
  - id: pretty-format-rust
    args:
    - --autofix
  - id: pretty-format-yaml
    args:
    - --autofix
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.8.0.4
  hooks:
  - id: shellcheck
